language: python

python:
  - "2.7"

addons:
  apt:
    packages:
    - samtools
    
before_install:
  # Install Miniconda
  - travis_retry wget http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh
  - chmod +x miniconda.sh
  - ./miniconda.sh -b
  - export PATH=/home/travis/miniconda/bin:$PATH
  - conda update --yes conda
  # Install bwa
  - cd test
  - git clone https://github.com/lh3/bwa.git
  - cd bwa
  - git checkout tags/0.7.12
  - make
  - cd ..
  - PATH=`pwd`/bwa:$PATH
  # Install bedtools
  - git clone https://github.com/arq5x/bedtools2.git
  - cd bedtools2
  - git checkout tags/v2.25.0
  - make
  - cd ..
  - PATH=`pwd`/bedtools2/bin:$PATH
  - cd ..

install:
 - conda install --yes numpy=1.9.1 
 - conda install --yes tox
 - python setup.py install

script: 
 - cd test && py.test